---
- name: Install AWS CLI v2
  hosts: all
  become: true
  tasks:
    - name: Download AWS CLI v2 package
      ansible.builtin.get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest: "/tmp/awscliv2.zip"

    - name: Unzip AWS CLI v2 package
      ansible.builtin.unarchive:
        src: "/tmp/awscliv2.zip"
        dest: "/tmp"
        remote_src: true

    - name: Run AWS CLI v2 installer
      ansible.builtin.command: >
        sudo /tmp/aws/install
      args:
        creates: /usr/local/bin/aws

    - name: Check AWS CLI version
      ansible.builtin.command: "aws --version"
      register: aws_cli_version
      changed_when: false

    - name: Print AWS CLI version
      ansible.builtin.debug:
        msg: "AWS CLI version: {{ aws_cli_version.stdout }}"
