---
- name: Install Java 17 with Amazon Corretto and check version
  hosts: all
  become: true
  tasks:
    - name: Install Java 17 with Amazon Corretto
      yum:
        name: java-17-amazon-corretto-headless
        state: present

    - name: Check Java version
      command: java --version
      register: java_version_output

    - debug:
        var: java_version_output.stdout_lines


